controllers:
    resource: '../src/Controller/'
    type: attribute
index:
    path: /
    controller: App\Controller\DefaultController::home
    defaults: {}

app_login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: [POST]

app_logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: [POST]
