framework:
    secret: '%env(APP_SECRET)%'

    # Notez que la session ne sera démarrée QUE si vous la lisez ou y écrivez.
    session: true

    # esi: true
    # fragments: true

    trusted_proxies: '127.0.0.1,REMOTE_ADDR'
    trusted_hosts: ['^localhost$', '^127\.0\.0\.1$']

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
