lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: '%env(JWT_PASSPHRASE)%'  # Ajoute ici ton mot de passe pour la clé privée
    token_ttl: 3600  # TTL des tokens (par exemple 1 heure)
